services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:17.5
    ports:
      - "5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgres/data
    restart: on-failure

volumes:
  postgres_data:
    driver: local