networks:
  product-network:
    driver: bridge

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:17.5
    ports:
      - "5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgres/data
    restart: on-failure
    networks:
      - product-network

  # TODO: ./gradlew clean build
  # TODO: docker-compose build --no-cache
  # TODO: docker-compose up -d
  product-service:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      DB_URL: ${DB_URL}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
    networks:
      - product-network

volumes:
  postgres_data:
    driver: local