server:
  port: ${SERVER_PORT}

spring:
  application:
    name: product-service

  profiles:
    active: ${ACTIVE_PROFILE:local}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    #open-in-view: false
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
