server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api

spring:
  application:
    name: product-service

  profiles:
    active: ${ACTIVE_PROFILE:local}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: false

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
      base-path: "/actuator"
  endpoint:
    health:
      show-details: always
      show-components: always
