CREATE SEQUENCE IF NOT EXISTS products_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE couriers
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username     VARCHAR(255)                            NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    phone        VARCHAR(255)                            NOT NULL,
    password     VARCHAR(255)                            NOT NULL,
    role         VARCHAR(255)                            NOT NULL,
    first_name   VARCHAR(255)                            NOT NULL,
    last_name    VARCHAR(255)                            NOT NULL,
    vehicle_type VARCHAR(255),
    CONSTRAINT pk_couriers PRIMARY KEY (id)
);

CREATE TABLE delivery
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type                 VARCHAR(31),
    delivery_time        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by_user_id   BIGINT                                  NOT NULL,
    status               VARCHAR(255)                            NOT NULL,
    pickup_point_address VARCHAR(255),
    courier_id           BIGINT,
    delivery_address     VARCHAR(255),
    CONSTRAINT pk_delivery PRIMARY KEY (id)
);

CREATE TABLE pickup_points
(
    contact_id   BIGINT,
    rating       DECIMAL,
    country      VARCHAR(255) NOT NULL,
    region       VARCHAR(255) NOT NULL,
    city         VARCHAR(255) NOT NULL,
    street       VARCHAR(255) NOT NULL,
    house_number VARCHAR(255) NOT NULL,
    entrance     VARCHAR(255) NOT NULL,
    open_time    VARCHAR(255),
    close_time   VARCHAR(255),
    CONSTRAINT pk_pickup_points PRIMARY KEY (country, region, city, street, house_number, entrance)
);

CREATE TABLE point_contacts_info
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone_number VARCHAR(255)                            NOT NULL,
    site         VARCHAR(255),
    CONSTRAINT pk_point_contacts_info PRIMARY KEY (id)
);

CREATE TABLE product_photos
(
    product_id BIGINT       NOT NULL,
    photos     VARCHAR(255) NOT NULL
);

CREATE TABLE products
(
    id          BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    price       DECIMAL      NOT NULL,
    discount    DOUBLE PRECISION,
    category    VARCHAR(255) NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    phone      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    role       VARCHAR(255)                            NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE couriers
    ADD CONSTRAINT uc_couriers_email UNIQUE (email);

ALTER TABLE couriers
    ADD CONSTRAINT uc_couriers_phone UNIQUE (phone);

ALTER TABLE couriers
    ADD CONSTRAINT uc_couriers_username UNIQUE (username);

ALTER TABLE point_contacts_info
    ADD CONSTRAINT uc_point_contacts_info_phonenumber UNIQUE (phone_number);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone UNIQUE (phone);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE delivery
    ADD CONSTRAINT FK_DELIVERY_ON_COURIER FOREIGN KEY (courier_id) REFERENCES couriers (id);

ALTER TABLE delivery
    ADD CONSTRAINT FK_DELIVERY_ON_CREATED_BY_USER FOREIGN KEY (created_by_user_id) REFERENCES users (id);

ALTER TABLE pickup_points
    ADD CONSTRAINT FK_PICKUP_POINTS_ON_CONTACT FOREIGN KEY (contact_id) REFERENCES point_contacts_info (id);

ALTER TABLE product_photos
    ADD CONSTRAINT fk_product_photos_on_product FOREIGN KEY (product_id) REFERENCES products (id);